export const WEATHER_CURRENT_BEGIN = 'WEATHER_CURRENT_BEGIN';
export const WEATHER_CURRENT_SUCCESS = 'WEATHER_CURRENT_SUCCESS';
export const WEATHER_CURRENT_ERROR = 'WEATHER_CURRENT_ERROR';
export const WEATHER_FORECAST_BEGIN = 'WEATHER_FORECAST_BEGIN';
export const WEATHER_FORECAST_SUCCESS = 'WEATHER_FORECAST_SUCCESS';
export const WEATHER_FORECAST_ERROR = 'WEATHER_FORECAST_ERROR';
